backend:
  name: github
  repo: mlabmt/PIR_PORTAL
  branch: main
  base_url: https://pirpolska.netlify.app
  auth_endpoint: /api/auth

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "news"
    label: "Wiadomości"
    folder: "src/content/news"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Tytuł", name: "title", widget: "string" }
      - { label: "Data Publikacji", name: "date", widget: "datetime" }
      - { label: "Tag", name: "tag", widget: "select", options: ["Hazard", "Legislacja", "Komunikat"] }
      - { label: "Opis (SEO)", name: "description", widget: "string" }
      - { label: "Treść Artykułu", name: "body", widget: "markdown" }
